---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# name in upstream package repository or registry
upstream_package_name: bootupd
upstream_tag_template: v{version}

downstream_package_name: rust-bootupd

specfile_path: contrib/packaging/bootupd.spec

files_to_sync:
  - .packit.yaml

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-9-x86_64
      - centos-stream-10-x86_64
      - fedora-42-x86_64
      - fedora-rawhide-x86_64

  - job: tests
    trigger: pull_request
    targets:
      - fedora-42-x86_64
    tmt_plan: /tmt/plans/integration

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      fedora-rawhide:
        fast_forward_merge_into: [fedora-latest-stable]

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-all
